# 🏠 House Price Prediction using Linear Regression

# 📌 Objective
Predict House prices using:
- Living Area (GrLivArea)
- Number of Bedrooms (BedroomAbvGr)
- Number of Bathrooms (FullBath)

---

# 🛠️ Tech Stack
- Python
- Pandas
- Scikit-learn
- Matplotlib

In [5]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [6]:
## 📥 Load Dataset

In [9]:
# Load dataset
df = pd.read_csv(r"C:\House Price Prediction\data\train.csv")

# Preview data
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [10]:
## 📊 Data Understanding

In [11]:
# Check info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [12]:
# Select required columns
features = ["GrLivArea", "BedroomAbvGr", "FullBath"]
target = "SalePrice"

df = df[features + [target]]

df.head()

   GrLivArea  BedroomAbvGr  FullBath  SalePrice
0       1710             3         2     208500
1       1262             3         2     181500
2       1786             3         2     223500
3       1717             3         1     140000
4       2198             4         2     250000

In [13]:
## 🧹 Data Cleaning